[package]
name = "symphonia-adapter-mousiki"
description = "Adapter to use mousiki pure-Rust Opus decoder with Symphonia"
version = "0.1.1"
license = "LGPL-2.1"
edition = "2024"
rust-version = "1.85"

[dependencies]
# mousiki = { path = "/home/ymsr/Documents/Repos/mousiki-recovered", features = ["fixed_point"] }
mousiki = { git = "https://github.com/mlm-games/mousiki-recovered", features = [
    "fixed_point",
] }
symphonia-core = "0.6"
log = "0.4"
