[package]
name = "symphonia-adapter-oporus"
description = "Adapter to use oporus pure-Rust Opus decoder with Symphonia"
version = "0.1.1"
license = "LGPL-2.1"
edition = "2024"
rust-version = "1.85"

[dependencies]
oporus = { version = "0.2.4", features = ["fixed_point"] }
symphonia-core = "0.6"
log = "0.4"
